---
########################################################################
#
# Playbook to install & configure the bungee proxy. 
#
# Requires ROOT Access on the box to execute 
#
########################################################################

- hosts: bungee-spigot
  become: true
  tasks:

  - name: Create Users on the OS
    user:
      name: "{{ item }}"
      state: present
    loop:
      "{{ sp_users }}"

  - name: Create Folders for Application Instances
    file:
      path: /home/INNO_Utils/bungee-spigot
      state: directory
      recurse: true

  - name: Create Folders for the Bungee Chord Setup
    file:
      path: /home/INNO_Utils/bungee-spigot/bungee
      state: directory
      recurse: true

  - include_role: 
      name: bungee-chord